// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: MuncCore.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PbNetworkResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MuncEventId uint32 `protobuf:"varint,1,opt,name=muncEventId,proto3" json:"muncEventId,omitempty"`
	Message     []byte `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *PbNetworkResp) Reset() {
	*x = PbNetworkResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MuncCore_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PbNetworkResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbNetworkResp) ProtoMessage() {}

func (x *PbNetworkResp) ProtoReflect() protoreflect.Message {
	mi := &file_MuncCore_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbNetworkResp.ProtoReflect.Descriptor instead.
func (*PbNetworkResp) Descriptor() ([]byte, []int) {
	return file_MuncCore_proto_rawDescGZIP(), []int{0}
}

func (x *PbNetworkResp) GetMuncEventId() uint32 {
	if x != nil {
		return x.MuncEventId
	}
	return 0
}

func (x *PbNetworkResp) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

type PbNetworkReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MuncEventId uint32 `protobuf:"varint,1,opt,name=muncEventId,proto3" json:"muncEventId,omitempty"`
	UserId      string `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	RoomName    string `protobuf:"bytes,3,opt,name=roomName,proto3" json:"roomName,omitempty"`
	Message     []byte `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *PbNetworkReq) Reset() {
	*x = PbNetworkReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MuncCore_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PbNetworkReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbNetworkReq) ProtoMessage() {}

func (x *PbNetworkReq) ProtoReflect() protoreflect.Message {
	mi := &file_MuncCore_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbNetworkReq.ProtoReflect.Descriptor instead.
func (*PbNetworkReq) Descriptor() ([]byte, []int) {
	return file_MuncCore_proto_rawDescGZIP(), []int{1}
}

func (x *PbNetworkReq) GetMuncEventId() uint32 {
	if x != nil {
		return x.MuncEventId
	}
	return 0
}

func (x *PbNetworkReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PbNetworkReq) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *PbNetworkReq) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

// not in use
type PbUdpInit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientSendUtcTicks    *float64 `protobuf:"fixed64,1,opt,name=clientSendUtcTicks,proto3,oneof" json:"clientSendUtcTicks,omitempty"`
	ServerReceiveUtcTicks *float64 `protobuf:"fixed64,2,opt,name=serverReceiveUtcTicks,proto3,oneof" json:"serverReceiveUtcTicks,omitempty"`
	ServerSendUtcTicks    *float64 `protobuf:"fixed64,3,opt,name=serverSendUtcTicks,proto3,oneof" json:"serverSendUtcTicks,omitempty"`
	ClientReceiveUtcTicks *float64 `protobuf:"fixed64,4,opt,name=clientReceiveUtcTicks,proto3,oneof" json:"clientReceiveUtcTicks,omitempty"`
}

func (x *PbUdpInit) Reset() {
	*x = PbUdpInit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MuncCore_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PbUdpInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbUdpInit) ProtoMessage() {}

func (x *PbUdpInit) ProtoReflect() protoreflect.Message {
	mi := &file_MuncCore_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbUdpInit.ProtoReflect.Descriptor instead.
func (*PbUdpInit) Descriptor() ([]byte, []int) {
	return file_MuncCore_proto_rawDescGZIP(), []int{2}
}

func (x *PbUdpInit) GetClientSendUtcTicks() float64 {
	if x != nil && x.ClientSendUtcTicks != nil {
		return *x.ClientSendUtcTicks
	}
	return 0
}

func (x *PbUdpInit) GetServerReceiveUtcTicks() float64 {
	if x != nil && x.ServerReceiveUtcTicks != nil {
		return *x.ServerReceiveUtcTicks
	}
	return 0
}

func (x *PbUdpInit) GetServerSendUtcTicks() float64 {
	if x != nil && x.ServerSendUtcTicks != nil {
		return *x.ServerSendUtcTicks
	}
	return 0
}

func (x *PbUdpInit) GetClientReceiveUtcTicks() float64 {
	if x != nil && x.ClientReceiveUtcTicks != nil {
		return *x.ClientReceiveUtcTicks
	}
	return 0
}

// not in use
type BatchedData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data [][]byte `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *BatchedData) Reset() {
	*x = BatchedData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MuncCore_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchedData) ProtoMessage() {}

func (x *BatchedData) ProtoReflect() protoreflect.Message {
	mi := &file_MuncCore_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchedData.ProtoReflect.Descriptor instead.
func (*BatchedData) Descriptor() ([]byte, []int) {
	return file_MuncCore_proto_rawDescGZIP(), []int{3}
}

func (x *BatchedData) GetData() [][]byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type MuncFailure struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	ErrorId uint32 `protobuf:"varint,2,opt,name=errorId,proto3" json:"errorId,omitempty"`
}

func (x *MuncFailure) Reset() {
	*x = MuncFailure{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MuncCore_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MuncFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MuncFailure) ProtoMessage() {}

func (x *MuncFailure) ProtoReflect() protoreflect.Message {
	mi := &file_MuncCore_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MuncFailure.ProtoReflect.Descriptor instead.
func (*MuncFailure) Descriptor() ([]byte, []int) {
	return file_MuncCore_proto_rawDescGZIP(), []int{4}
}

func (x *MuncFailure) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MuncFailure) GetErrorId() uint32 {
	if x != nil {
		return x.ErrorId
	}
	return 0
}

var File_MuncCore_proto protoreflect.FileDescriptor

var file_MuncCore_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x4d, 0x75, 0x6e, 0x63, 0x43, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x4b, 0x0a, 0x0d, 0x50, 0x62, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x75, 0x6e, 0x63, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x6d, 0x75, 0x6e, 0x63, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x7e, 0x0a,
	0x0c, 0x50, 0x62, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x20, 0x0a,
	0x0b, 0x6d, 0x75, 0x6e, 0x63, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0b, 0x6d, 0x75, 0x6e, 0x63, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xcd, 0x02,
	0x0a, 0x09, 0x50, 0x62, 0x55, 0x64, 0x70, 0x49, 0x6e, 0x69, 0x74, 0x12, 0x33, 0x0a, 0x12, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x6e, 0x64, 0x55, 0x74, 0x63, 0x54, 0x69, 0x63, 0x6b,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x12, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x53, 0x65, 0x6e, 0x64, 0x55, 0x74, 0x63, 0x54, 0x69, 0x63, 0x6b, 0x73, 0x88, 0x01, 0x01,
	0x12, 0x39, 0x0a, 0x15, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x55, 0x74, 0x63, 0x54, 0x69, 0x63, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x48,
	0x01, 0x52, 0x15, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65,
	0x55, 0x74, 0x63, 0x54, 0x69, 0x63, 0x6b, 0x73, 0x88, 0x01, 0x01, 0x12, 0x33, 0x0a, 0x12, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x65, 0x6e, 0x64, 0x55, 0x74, 0x63, 0x54, 0x69, 0x63, 0x6b,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x48, 0x02, 0x52, 0x12, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x53, 0x65, 0x6e, 0x64, 0x55, 0x74, 0x63, 0x54, 0x69, 0x63, 0x6b, 0x73, 0x88, 0x01, 0x01,
	0x12, 0x39, 0x0a, 0x15, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x55, 0x74, 0x63, 0x54, 0x69, 0x63, 0x6b, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x48,
	0x03, 0x52, 0x15, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65,
	0x55, 0x74, 0x63, 0x54, 0x69, 0x63, 0x6b, 0x73, 0x88, 0x01, 0x01, 0x42, 0x15, 0x0a, 0x13, 0x5f,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x6e, 0x64, 0x55, 0x74, 0x63, 0x54, 0x69, 0x63,
	0x6b, 0x73, 0x42, 0x18, 0x0a, 0x16, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x55, 0x74, 0x63, 0x54, 0x69, 0x63, 0x6b, 0x73, 0x42, 0x15, 0x0a, 0x13,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x65, 0x6e, 0x64, 0x55, 0x74, 0x63, 0x54, 0x69,
	0x63, 0x6b, 0x73, 0x42, 0x18, 0x0a, 0x16, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x55, 0x74, 0x63, 0x54, 0x69, 0x63, 0x6b, 0x73, 0x22, 0x21, 0x0a,
	0x0b, 0x42, 0x61, 0x74, 0x63, 0x68, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x41, 0x0a, 0x0b, 0x4d, 0x75, 0x6e, 0x63, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x49, 0x64, 0x42, 0x0b, 0x5a, 0x09, 0x6d, 0x75, 0x6e, 0x63, 0x2f, 0x63, 0x6f, 0x72, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_MuncCore_proto_rawDescOnce sync.Once
	file_MuncCore_proto_rawDescData = file_MuncCore_proto_rawDesc
)

func file_MuncCore_proto_rawDescGZIP() []byte {
	file_MuncCore_proto_rawDescOnce.Do(func() {
		file_MuncCore_proto_rawDescData = protoimpl.X.CompressGZIP(file_MuncCore_proto_rawDescData)
	})
	return file_MuncCore_proto_rawDescData
}

var file_MuncCore_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_MuncCore_proto_goTypes = []interface{}{
	(*PbNetworkResp)(nil), // 0: PbNetworkResp
	(*PbNetworkReq)(nil),  // 1: PbNetworkReq
	(*PbUdpInit)(nil),     // 2: PbUdpInit
	(*BatchedData)(nil),   // 3: BatchedData
	(*MuncFailure)(nil),   // 4: MuncFailure
}
var file_MuncCore_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_MuncCore_proto_init() }
func file_MuncCore_proto_init() {
	if File_MuncCore_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_MuncCore_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PbNetworkResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MuncCore_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PbNetworkReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MuncCore_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PbUdpInit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MuncCore_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchedData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MuncCore_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MuncFailure); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_MuncCore_proto_msgTypes[2].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_MuncCore_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_MuncCore_proto_goTypes,
		DependencyIndexes: file_MuncCore_proto_depIdxs,
		MessageInfos:      file_MuncCore_proto_msgTypes,
	}.Build()
	File_MuncCore_proto = out.File
	file_MuncCore_proto_rawDesc = nil
	file_MuncCore_proto_goTypes = nil
	file_MuncCore_proto_depIdxs = nil
}
