// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: MuncDemo.proto

package demo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	roomData "munc/roomData"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PbMeeple struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TransformData *roomData.PbTransform   `protobuf:"bytes,1,opt,name=transformData,proto3,oneof" json:"transformData,omitempty"`
	HexColor      []byte                  `protobuf:"bytes,2,opt,name=hexColor,proto3,oneof" json:"hexColor,omitempty"`
	Clothes       *PbMeeple_ClothingFlags `protobuf:"bytes,3,opt,name=clothes,proto3,oneof" json:"clothes,omitempty"`
}

func (x *PbMeeple) Reset() {
	*x = PbMeeple{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MuncDemo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PbMeeple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbMeeple) ProtoMessage() {}

func (x *PbMeeple) ProtoReflect() protoreflect.Message {
	mi := &file_MuncDemo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbMeeple.ProtoReflect.Descriptor instead.
func (*PbMeeple) Descriptor() ([]byte, []int) {
	return file_MuncDemo_proto_rawDescGZIP(), []int{0}
}

func (x *PbMeeple) GetTransformData() *roomData.PbTransform {
	if x != nil {
		return x.TransformData
	}
	return nil
}

func (x *PbMeeple) GetHexColor() []byte {
	if x != nil {
		return x.HexColor
	}
	return nil
}

func (x *PbMeeple) GetClothes() *PbMeeple_ClothingFlags {
	if x != nil {
		return x.Clothes
	}
	return nil
}

type PbMeeple_ClothingFlags struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HasHat   bool `protobuf:"varint,1,opt,name=hasHat,proto3" json:"hasHat,omitempty"`
	HasShoes bool `protobuf:"varint,2,opt,name=hasShoes,proto3" json:"hasShoes,omitempty"`
}

func (x *PbMeeple_ClothingFlags) Reset() {
	*x = PbMeeple_ClothingFlags{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MuncDemo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PbMeeple_ClothingFlags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbMeeple_ClothingFlags) ProtoMessage() {}

func (x *PbMeeple_ClothingFlags) ProtoReflect() protoreflect.Message {
	mi := &file_MuncDemo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbMeeple_ClothingFlags.ProtoReflect.Descriptor instead.
func (*PbMeeple_ClothingFlags) Descriptor() ([]byte, []int) {
	return file_MuncDemo_proto_rawDescGZIP(), []int{0, 0}
}

func (x *PbMeeple_ClothingFlags) GetHasHat() bool {
	if x != nil {
		return x.HasHat
	}
	return false
}

func (x *PbMeeple_ClothingFlags) GetHasShoes() bool {
	if x != nil {
		return x.HasShoes
	}
	return false
}

var File_MuncDemo_proto protoreflect.FileDescriptor

var file_MuncDemo_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x4d, 0x75, 0x6e, 0x63, 0x44, 0x65, 0x6d, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x0e, 0x4d, 0x75, 0x6e, 0x63, 0x52, 0x6f, 0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x8c, 0x02, 0x0a, 0x08, 0x50, 0x62, 0x4d, 0x65, 0x65, 0x70, 0x6c, 0x65, 0x12, 0x37, 0x0a,
	0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x50, 0x62, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f,
	0x72, 0x6d, 0x48, 0x00, 0x52, 0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x44,
	0x61, 0x74, 0x61, 0x88, 0x01, 0x01, 0x12, 0x1f, 0x0a, 0x08, 0x68, 0x65, 0x78, 0x43, 0x6f, 0x6c,
	0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x01, 0x52, 0x08, 0x68, 0x65, 0x78, 0x43,
	0x6f, 0x6c, 0x6f, 0x72, 0x88, 0x01, 0x01, 0x12, 0x36, 0x0a, 0x07, 0x63, 0x6c, 0x6f, 0x74, 0x68,
	0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x50, 0x62, 0x4d, 0x65, 0x65,
	0x70, 0x6c, 0x65, 0x2e, 0x43, 0x6c, 0x6f, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x46, 0x6c, 0x61, 0x67,
	0x73, 0x48, 0x02, 0x52, 0x07, 0x63, 0x6c, 0x6f, 0x74, 0x68, 0x65, 0x73, 0x88, 0x01, 0x01, 0x1a,
	0x43, 0x0a, 0x0d, 0x43, 0x6c, 0x6f, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x46, 0x6c, 0x61, 0x67, 0x73,
	0x12, 0x16, 0x0a, 0x06, 0x68, 0x61, 0x73, 0x48, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x68, 0x61, 0x73, 0x48, 0x61, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x61, 0x73, 0x53,
	0x68, 0x6f, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x68, 0x61, 0x73, 0x53,
	0x68, 0x6f, 0x65, 0x73, 0x42, 0x10, 0x0a, 0x0e, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f,
	0x72, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x68, 0x65, 0x78, 0x43, 0x6f,
	0x6c, 0x6f, 0x72, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x63, 0x6c, 0x6f, 0x74, 0x68, 0x65, 0x73, 0x42,
	0x0b, 0x5a, 0x09, 0x6d, 0x75, 0x6e, 0x63, 0x2f, 0x64, 0x65, 0x6d, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_MuncDemo_proto_rawDescOnce sync.Once
	file_MuncDemo_proto_rawDescData = file_MuncDemo_proto_rawDesc
)

func file_MuncDemo_proto_rawDescGZIP() []byte {
	file_MuncDemo_proto_rawDescOnce.Do(func() {
		file_MuncDemo_proto_rawDescData = protoimpl.X.CompressGZIP(file_MuncDemo_proto_rawDescData)
	})
	return file_MuncDemo_proto_rawDescData
}

var file_MuncDemo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_MuncDemo_proto_goTypes = []interface{}{
	(*PbMeeple)(nil),               // 0: PbMeeple
	(*PbMeeple_ClothingFlags)(nil), // 1: PbMeeple.ClothingFlags
	(*roomData.PbTransform)(nil),   // 2: PbTransform
}
var file_MuncDemo_proto_depIdxs = []int32{
	2, // 0: PbMeeple.transformData:type_name -> PbTransform
	1, // 1: PbMeeple.clothes:type_name -> PbMeeple.ClothingFlags
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_MuncDemo_proto_init() }
func file_MuncDemo_proto_init() {
	if File_MuncDemo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_MuncDemo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PbMeeple); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MuncDemo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PbMeeple_ClothingFlags); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_MuncDemo_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_MuncDemo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_MuncDemo_proto_goTypes,
		DependencyIndexes: file_MuncDemo_proto_depIdxs,
		MessageInfos:      file_MuncDemo_proto_msgTypes,
	}.Build()
	File_MuncDemo_proto = out.File
	file_MuncDemo_proto_rawDesc = nil
	file_MuncDemo_proto_goTypes = nil
	file_MuncDemo_proto_depIdxs = nil
}
