// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: MuncRoom.proto

package roomData

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Platform int32

const (
	Platform_DESKTOP    Platform = 0
	Platform_HOLOLENS   Platform = 1
	Platform_TABLET     Platform = 2
	Platform_MAGIC_LEAP Platform = 3
	Platform_QUEST      Platform = 4
)

// Enum value maps for Platform.
var (
	Platform_name = map[int32]string{
		0: "DESKTOP",
		1: "HOLOLENS",
		2: "TABLET",
		3: "MAGIC_LEAP",
		4: "QUEST",
	}
	Platform_value = map[string]int32{
		"DESKTOP":    0,
		"HOLOLENS":   1,
		"TABLET":     2,
		"MAGIC_LEAP": 3,
		"QUEST":      4,
	}
)

func (x Platform) Enum() *Platform {
	p := new(Platform)
	*p = x
	return p
}

func (x Platform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Platform) Descriptor() protoreflect.EnumDescriptor {
	return file_MuncRoom_proto_enumTypes[0].Descriptor()
}

func (Platform) Type() protoreflect.EnumType {
	return &file_MuncRoom_proto_enumTypes[0]
}

func (x Platform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Platform.Descriptor instead.
func (Platform) EnumDescriptor() ([]byte, []int) {
	return file_MuncRoom_proto_rawDescGZIP(), []int{0}
}

type ConnectionInitReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId       string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	SessionToken string `protobuf:"bytes,2,opt,name=sessionToken,proto3" json:"sessionToken,omitempty"`
}

func (x *ConnectionInitReq) Reset() {
	*x = ConnectionInitReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MuncRoom_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectionInitReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionInitReq) ProtoMessage() {}

func (x *ConnectionInitReq) ProtoReflect() protoreflect.Message {
	mi := &file_MuncRoom_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionInitReq.ProtoReflect.Descriptor instead.
func (*ConnectionInitReq) Descriptor() ([]byte, []int) {
	return file_MuncRoom_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectionInitReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ConnectionInitReq) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type ConnectionInitResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *ConnectionInitResp) Reset() {
	*x = ConnectionInitResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MuncRoom_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectionInitResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionInitResp) ProtoMessage() {}

func (x *ConnectionInitResp) ProtoReflect() protoreflect.Message {
	mi := &file_MuncRoom_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionInitResp.ProtoReflect.Descriptor instead.
func (*ConnectionInitResp) Descriptor() ([]byte, []int) {
	return file_MuncRoom_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectionInitResp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ObjectUpdateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *ObjectUpdateResp) Reset() {
	*x = ObjectUpdateResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MuncRoom_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectUpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectUpdateResp) ProtoMessage() {}

func (x *ObjectUpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_MuncRoom_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectUpdateResp.ProtoReflect.Descriptor instead.
func (*ObjectUpdateResp) Descriptor() ([]byte, []int) {
	return file_MuncRoom_proto_rawDescGZIP(), []int{2}
}

func (x *ObjectUpdateResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ReleaseObjectsOwnership struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjectId []string `protobuf:"bytes,1,rep,name=objectId,proto3" json:"objectId,omitempty"`
}

func (x *ReleaseObjectsOwnership) Reset() {
	*x = ReleaseObjectsOwnership{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MuncRoom_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReleaseObjectsOwnership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseObjectsOwnership) ProtoMessage() {}

func (x *ReleaseObjectsOwnership) ProtoReflect() protoreflect.Message {
	mi := &file_MuncRoom_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseObjectsOwnership.ProtoReflect.Descriptor instead.
func (*ReleaseObjectsOwnership) Descriptor() ([]byte, []int) {
	return file_MuncRoom_proto_rawDescGZIP(), []int{3}
}

func (x *ReleaseObjectsOwnership) GetObjectId() []string {
	if x != nil {
		return x.ObjectId
	}
	return nil
}

type RequestBoolResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results map[string]bool `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *RequestBoolResp) Reset() {
	*x = RequestBoolResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MuncRoom_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestBoolResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestBoolResp) ProtoMessage() {}

func (x *RequestBoolResp) ProtoReflect() protoreflect.Message {
	mi := &file_MuncRoom_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestBoolResp.ProtoReflect.Descriptor instead.
func (*RequestBoolResp) Descriptor() ([]byte, []int) {
	return file_MuncRoom_proto_rawDescGZIP(), []int{4}
}

func (x *RequestBoolResp) GetResults() map[string]bool {
	if x != nil {
		return x.Results
	}
	return nil
}

type RoomConnectReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nickname string `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	RoomName string `protobuf:"bytes,2,opt,name=roomName,proto3" json:"roomName,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *RoomConnectReq) Reset() {
	*x = RoomConnectReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MuncRoom_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomConnectReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomConnectReq) ProtoMessage() {}

func (x *RoomConnectReq) ProtoReflect() protoreflect.Message {
	mi := &file_MuncRoom_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomConnectReq.ProtoReflect.Descriptor instead.
func (*RoomConnectReq) Descriptor() ([]byte, []int) {
	return file_MuncRoom_proto_rawDescGZIP(), []int{5}
}

func (x *RoomConnectReq) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *RoomConnectReq) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *RoomConnectReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RoomConnectResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomName     string       `protobuf:"bytes,1,opt,name=roomName,proto3" json:"roomName,omitempty"`
	CurrentState *PbRoomState `protobuf:"bytes,2,opt,name=currentState,proto3" json:"currentState,omitempty"`
}

func (x *RoomConnectResp) Reset() {
	*x = RoomConnectResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MuncRoom_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomConnectResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomConnectResp) ProtoMessage() {}

func (x *RoomConnectResp) ProtoReflect() protoreflect.Message {
	mi := &file_MuncRoom_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomConnectResp.ProtoReflect.Descriptor instead.
func (*RoomConnectResp) Descriptor() ([]byte, []int) {
	return file_MuncRoom_proto_rawDescGZIP(), []int{6}
}

func (x *RoomConnectResp) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *RoomConnectResp) GetCurrentState() *PbRoomState {
	if x != nil {
		return x.CurrentState
	}
	return nil
}

type RoomJoinReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PositionPort int32    `protobuf:"varint,1,opt,name=positionPort,proto3" json:"positionPort,omitempty"`
	VoipPort     int32    `protobuf:"varint,2,opt,name=voipPort,proto3" json:"voipPort,omitempty"`
	Platform     Platform `protobuf:"varint,3,opt,name=platform,proto3,enum=Platform" json:"platform,omitempty"`
}

func (x *RoomJoinReq) Reset() {
	*x = RoomJoinReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MuncRoom_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomJoinReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomJoinReq) ProtoMessage() {}

func (x *RoomJoinReq) ProtoReflect() protoreflect.Message {
	mi := &file_MuncRoom_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomJoinReq.ProtoReflect.Descriptor instead.
func (*RoomJoinReq) Descriptor() ([]byte, []int) {
	return file_MuncRoom_proto_rawDescGZIP(), []int{7}
}

func (x *RoomJoinReq) GetPositionPort() int32 {
	if x != nil {
		return x.PositionPort
	}
	return 0
}

func (x *RoomJoinReq) GetVoipPort() int32 {
	if x != nil {
		return x.VoipPort
	}
	return 0
}

func (x *RoomJoinReq) GetPlatform() Platform {
	if x != nil {
		return x.Platform
	}
	return Platform_DESKTOP
}

type RoomJoinResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PositionServerPort int32 `protobuf:"varint,1,opt,name=positionServerPort,proto3" json:"positionServerPort,omitempty"`
	VoipServerPort     int32 `protobuf:"varint,2,opt,name=voipServerPort,proto3" json:"voipServerPort,omitempty"`
}

func (x *RoomJoinResp) Reset() {
	*x = RoomJoinResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MuncRoom_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomJoinResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomJoinResp) ProtoMessage() {}

func (x *RoomJoinResp) ProtoReflect() protoreflect.Message {
	mi := &file_MuncRoom_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomJoinResp.ProtoReflect.Descriptor instead.
func (*RoomJoinResp) Descriptor() ([]byte, []int) {
	return file_MuncRoom_proto_rawDescGZIP(), []int{8}
}

func (x *RoomJoinResp) GetPositionServerPort() int32 {
	if x != nil {
		return x.PositionServerPort
	}
	return 0
}

func (x *RoomJoinResp) GetVoipServerPort() int32 {
	if x != nil {
		return x.VoipServerPort
	}
	return 0
}

type PbRoomState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AllObjects []*RoomStateEvt `protobuf:"bytes,1,rep,name=allObjects,proto3" json:"allObjects,omitempty"`
}

func (x *PbRoomState) Reset() {
	*x = PbRoomState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MuncRoom_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PbRoomState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbRoomState) ProtoMessage() {}

func (x *PbRoomState) ProtoReflect() protoreflect.Message {
	mi := &file_MuncRoom_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbRoomState.ProtoReflect.Descriptor instead.
func (*PbRoomState) Descriptor() ([]byte, []int) {
	return file_MuncRoom_proto_rawDescGZIP(), []int{9}
}

func (x *PbRoomState) GetAllObjects() []*RoomStateEvt {
	if x != nil {
		return x.AllObjects
	}
	return nil
}

type RoomStateEvt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjectId string      `protobuf:"bytes,1,opt,name=objectId,proto3" json:"objectId,omitempty"`
	OwnerId  string      `protobuf:"bytes,2,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	Payload  []*StateObj `protobuf:"bytes,3,rep,name=payload,proto3" json:"payload,omitempty"`
}

func (x *RoomStateEvt) Reset() {
	*x = RoomStateEvt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MuncRoom_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomStateEvt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomStateEvt) ProtoMessage() {}

func (x *RoomStateEvt) ProtoReflect() protoreflect.Message {
	mi := &file_MuncRoom_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomStateEvt.ProtoReflect.Descriptor instead.
func (*RoomStateEvt) Descriptor() ([]byte, []int) {
	return file_MuncRoom_proto_rawDescGZIP(), []int{10}
}

func (x *RoomStateEvt) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *RoomStateEvt) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *RoomStateEvt) GetPayload() []*StateObj {
	if x != nil {
		return x.Payload
	}
	return nil
}

type StateObj struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload *anypb.Any `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *StateObj) Reset() {
	*x = StateObj{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MuncRoom_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StateObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateObj) ProtoMessage() {}

func (x *StateObj) ProtoReflect() protoreflect.Message {
	mi := &file_MuncRoom_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateObj.ProtoReflect.Descriptor instead.
func (*StateObj) Descriptor() ([]byte, []int) {
	return file_MuncRoom_proto_rawDescGZIP(), []int{11}
}

func (x *StateObj) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

type PbMuncUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId        string       `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Name          string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Platform      *Platform    `protobuf:"varint,3,opt,name=platform,proto3,enum=Platform,oneof" json:"platform,omitempty"`
	TransformData *PbTransform `protobuf:"bytes,4,opt,name=transformData,proto3,oneof" json:"transformData,omitempty"`
}

func (x *PbMuncUser) Reset() {
	*x = PbMuncUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MuncRoom_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PbMuncUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbMuncUser) ProtoMessage() {}

func (x *PbMuncUser) ProtoReflect() protoreflect.Message {
	mi := &file_MuncRoom_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbMuncUser.ProtoReflect.Descriptor instead.
func (*PbMuncUser) Descriptor() ([]byte, []int) {
	return file_MuncRoom_proto_rawDescGZIP(), []int{12}
}

func (x *PbMuncUser) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PbMuncUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PbMuncUser) GetPlatform() Platform {
	if x != nil && x.Platform != nil {
		return *x.Platform
	}
	return Platform_DESKTOP
}

func (x *PbMuncUser) GetTransformData() *PbTransform {
	if x != nil {
		return x.TransformData
	}
	return nil
}

type PbMuncAvatar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId        string       `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Name          *string      `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Platform      *Platform    `protobuf:"varint,3,opt,name=platform,proto3,enum=Platform,oneof" json:"platform,omitempty"`
	TransformData *PbTransform `protobuf:"bytes,4,opt,name=transformData,proto3,oneof" json:"transformData,omitempty"`
}

func (x *PbMuncAvatar) Reset() {
	*x = PbMuncAvatar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MuncRoom_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PbMuncAvatar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbMuncAvatar) ProtoMessage() {}

func (x *PbMuncAvatar) ProtoReflect() protoreflect.Message {
	mi := &file_MuncRoom_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbMuncAvatar.ProtoReflect.Descriptor instead.
func (*PbMuncAvatar) Descriptor() ([]byte, []int) {
	return file_MuncRoom_proto_rawDescGZIP(), []int{13}
}

func (x *PbMuncAvatar) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PbMuncAvatar) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *PbMuncAvatar) GetPlatform() Platform {
	if x != nil && x.Platform != nil {
		return *x.Platform
	}
	return Platform_DESKTOP
}

func (x *PbMuncAvatar) GetTransformData() *PbTransform {
	if x != nil {
		return x.TransformData
	}
	return nil
}

type PbTransform struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Position *PbVect3 `protobuf:"bytes,1,opt,name=position,proto3,oneof" json:"position,omitempty"`
	Rotation *PbVect3 `protobuf:"bytes,2,opt,name=rotation,proto3,oneof" json:"rotation,omitempty"`
	Scale    *PbVect3 `protobuf:"bytes,3,opt,name=scale,proto3,oneof" json:"scale,omitempty"`
}

func (x *PbTransform) Reset() {
	*x = PbTransform{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MuncRoom_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PbTransform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbTransform) ProtoMessage() {}

func (x *PbTransform) ProtoReflect() protoreflect.Message {
	mi := &file_MuncRoom_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbTransform.ProtoReflect.Descriptor instead.
func (*PbTransform) Descriptor() ([]byte, []int) {
	return file_MuncRoom_proto_rawDescGZIP(), []int{14}
}

func (x *PbTransform) GetPosition() *PbVect3 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *PbTransform) GetRotation() *PbVect3 {
	if x != nil {
		return x.Rotation
	}
	return nil
}

func (x *PbTransform) GetScale() *PbVect3 {
	if x != nil {
		return x.Scale
	}
	return nil
}

type PbVect3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z float32 `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
}

func (x *PbVect3) Reset() {
	*x = PbVect3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MuncRoom_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PbVect3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbVect3) ProtoMessage() {}

func (x *PbVect3) ProtoReflect() protoreflect.Message {
	mi := &file_MuncRoom_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbVect3.ProtoReflect.Descriptor instead.
func (*PbVect3) Descriptor() ([]byte, []int) {
	return file_MuncRoom_proto_rawDescGZIP(), []int{15}
}

func (x *PbVect3) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PbVect3) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PbVect3) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

type UserJoinedRoomEvt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	RoomName    string `protobuf:"bytes,2,opt,name=roomName,proto3" json:"roomName,omitempty"`
	Nickname    string `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Reconnected bool   `protobuf:"varint,4,opt,name=reconnected,proto3" json:"reconnected,omitempty"` //default false
}

func (x *UserJoinedRoomEvt) Reset() {
	*x = UserJoinedRoomEvt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MuncRoom_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserJoinedRoomEvt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserJoinedRoomEvt) ProtoMessage() {}

func (x *UserJoinedRoomEvt) ProtoReflect() protoreflect.Message {
	mi := &file_MuncRoom_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserJoinedRoomEvt.ProtoReflect.Descriptor instead.
func (*UserJoinedRoomEvt) Descriptor() ([]byte, []int) {
	return file_MuncRoom_proto_rawDescGZIP(), []int{16}
}

func (x *UserJoinedRoomEvt) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserJoinedRoomEvt) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *UserJoinedRoomEvt) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserJoinedRoomEvt) GetReconnected() bool {
	if x != nil {
		return x.Reconnected
	}
	return false
}

type UserExitRoomEvt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId       string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	RoomName     string `protobuf:"bytes,2,opt,name=roomName,proto3" json:"roomName,omitempty"`
	Nickname     string `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Disconnected bool   `protobuf:"varint,4,opt,name=disconnected,proto3" json:"disconnected,omitempty"` //default false
}

func (x *UserExitRoomEvt) Reset() {
	*x = UserExitRoomEvt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MuncRoom_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserExitRoomEvt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserExitRoomEvt) ProtoMessage() {}

func (x *UserExitRoomEvt) ProtoReflect() protoreflect.Message {
	mi := &file_MuncRoom_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserExitRoomEvt.ProtoReflect.Descriptor instead.
func (*UserExitRoomEvt) Descriptor() ([]byte, []int) {
	return file_MuncRoom_proto_rawDescGZIP(), []int{17}
}

func (x *UserExitRoomEvt) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserExitRoomEvt) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *UserExitRoomEvt) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserExitRoomEvt) GetDisconnected() bool {
	if x != nil {
		return x.Disconnected
	}
	return false
}

type ExitRoomReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomName string `protobuf:"bytes,1,opt,name=roomName,proto3" json:"roomName,omitempty"`
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
}

func (x *ExitRoomReq) Reset() {
	*x = ExitRoomReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MuncRoom_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExitRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitRoomReq) ProtoMessage() {}

func (x *ExitRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_MuncRoom_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitRoomReq.ProtoReflect.Descriptor instead.
func (*ExitRoomReq) Descriptor() ([]byte, []int) {
	return file_MuncRoom_proto_rawDescGZIP(), []int{18}
}

func (x *ExitRoomReq) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *ExitRoomReq) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type RoomExitResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomName string `protobuf:"bytes,2,opt,name=roomName,proto3" json:"roomName,omitempty"`
}

func (x *RoomExitResp) Reset() {
	*x = RoomExitResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MuncRoom_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomExitResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomExitResp) ProtoMessage() {}

func (x *RoomExitResp) ProtoReflect() protoreflect.Message {
	mi := &file_MuncRoom_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomExitResp.ProtoReflect.Descriptor instead.
func (*RoomExitResp) Descriptor() ([]byte, []int) {
	return file_MuncRoom_proto_rawDescGZIP(), []int{19}
}

func (x *RoomExitResp) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

type ObjectDeleteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjectId string `protobuf:"bytes,1,opt,name=objectId,proto3" json:"objectId,omitempty"`
}

func (x *ObjectDeleteReq) Reset() {
	*x = ObjectDeleteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MuncRoom_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectDeleteReq) ProtoMessage() {}

func (x *ObjectDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_MuncRoom_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectDeleteReq.ProtoReflect.Descriptor instead.
func (*ObjectDeleteReq) Descriptor() ([]byte, []int) {
	return file_MuncRoom_proto_rawDescGZIP(), []int{20}
}

func (x *ObjectDeleteReq) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

type PbEolianAvatar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId        string                         `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Name          string                         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Platform      *Platform                      `protobuf:"varint,3,opt,name=platform,proto3,enum=Platform,oneof" json:"platform,omitempty"`
	TransformData *PbTransform                   `protobuf:"bytes,4,opt,name=transformData,proto3,oneof" json:"transformData,omitempty"`
	Version       string                         `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Settings      *PbEolianAvatar_AvatarSettings `protobuf:"bytes,6,opt,name=settings,proto3,oneof" json:"settings,omitempty"`
	Hands         *PbEolianAvatar_HandsData      `protobuf:"bytes,7,opt,name=hands,proto3,oneof" json:"hands,omitempty"`
}

func (x *PbEolianAvatar) Reset() {
	*x = PbEolianAvatar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MuncRoom_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PbEolianAvatar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbEolianAvatar) ProtoMessage() {}

func (x *PbEolianAvatar) ProtoReflect() protoreflect.Message {
	mi := &file_MuncRoom_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbEolianAvatar.ProtoReflect.Descriptor instead.
func (*PbEolianAvatar) Descriptor() ([]byte, []int) {
	return file_MuncRoom_proto_rawDescGZIP(), []int{21}
}

func (x *PbEolianAvatar) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PbEolianAvatar) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PbEolianAvatar) GetPlatform() Platform {
	if x != nil && x.Platform != nil {
		return *x.Platform
	}
	return Platform_DESKTOP
}

func (x *PbEolianAvatar) GetTransformData() *PbTransform {
	if x != nil {
		return x.TransformData
	}
	return nil
}

func (x *PbEolianAvatar) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PbEolianAvatar) GetSettings() *PbEolianAvatar_AvatarSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *PbEolianAvatar) GetHands() *PbEolianAvatar_HandsData {
	if x != nil {
		return x.Hands
	}
	return nil
}

type PbEolianAvatar_HandsData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Left  *PbEolianAvatar_HandsData_HandData `protobuf:"bytes,1,opt,name=left,proto3,oneof" json:"left,omitempty"`
	Right *PbEolianAvatar_HandsData_HandData `protobuf:"bytes,2,opt,name=right,proto3,oneof" json:"right,omitempty"`
}

func (x *PbEolianAvatar_HandsData) Reset() {
	*x = PbEolianAvatar_HandsData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MuncRoom_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PbEolianAvatar_HandsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbEolianAvatar_HandsData) ProtoMessage() {}

func (x *PbEolianAvatar_HandsData) ProtoReflect() protoreflect.Message {
	mi := &file_MuncRoom_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbEolianAvatar_HandsData.ProtoReflect.Descriptor instead.
func (*PbEolianAvatar_HandsData) Descriptor() ([]byte, []int) {
	return file_MuncRoom_proto_rawDescGZIP(), []int{21, 0}
}

func (x *PbEolianAvatar_HandsData) GetLeft() *PbEolianAvatar_HandsData_HandData {
	if x != nil {
		return x.Left
	}
	return nil
}

func (x *PbEolianAvatar_HandsData) GetRight() *PbEolianAvatar_HandsData_HandData {
	if x != nil {
		return x.Right
	}
	return nil
}

type PbEolianAvatar_AvatarSettings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShowBody       bool `protobuf:"varint,1,opt,name=showBody,proto3" json:"showBody,omitempty"`
	Mute           bool `protobuf:"varint,2,opt,name=mute,proto3" json:"mute,omitempty"`
	HasControl     bool `protobuf:"varint,3,opt,name=hasControl,proto3" json:"hasControl,omitempty"`
	HasMenuControl bool `protobuf:"varint,4,opt,name=hasMenuControl,proto3" json:"hasMenuControl,omitempty"`
}

func (x *PbEolianAvatar_AvatarSettings) Reset() {
	*x = PbEolianAvatar_AvatarSettings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MuncRoom_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PbEolianAvatar_AvatarSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbEolianAvatar_AvatarSettings) ProtoMessage() {}

func (x *PbEolianAvatar_AvatarSettings) ProtoReflect() protoreflect.Message {
	mi := &file_MuncRoom_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbEolianAvatar_AvatarSettings.ProtoReflect.Descriptor instead.
func (*PbEolianAvatar_AvatarSettings) Descriptor() ([]byte, []int) {
	return file_MuncRoom_proto_rawDescGZIP(), []int{21, 1}
}

func (x *PbEolianAvatar_AvatarSettings) GetShowBody() bool {
	if x != nil {
		return x.ShowBody
	}
	return false
}

func (x *PbEolianAvatar_AvatarSettings) GetMute() bool {
	if x != nil {
		return x.Mute
	}
	return false
}

func (x *PbEolianAvatar_AvatarSettings) GetHasControl() bool {
	if x != nil {
		return x.HasControl
	}
	return false
}

func (x *PbEolianAvatar_AvatarSettings) GetHasMenuControl() bool {
	if x != nil {
		return x.HasMenuControl
	}
	return false
}

type PbEolianAvatar_HandsData_HandData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Show   bool                                                    `protobuf:"varint,1,opt,name=show,proto3" json:"show,omitempty"`
	Joints map[uint32]*PbEolianAvatar_HandsData_HandData_JointData `protobuf:"bytes,2,rep,name=joints,proto3" json:"joints,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *PbEolianAvatar_HandsData_HandData) Reset() {
	*x = PbEolianAvatar_HandsData_HandData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MuncRoom_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PbEolianAvatar_HandsData_HandData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbEolianAvatar_HandsData_HandData) ProtoMessage() {}

func (x *PbEolianAvatar_HandsData_HandData) ProtoReflect() protoreflect.Message {
	mi := &file_MuncRoom_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbEolianAvatar_HandsData_HandData.ProtoReflect.Descriptor instead.
func (*PbEolianAvatar_HandsData_HandData) Descriptor() ([]byte, []int) {
	return file_MuncRoom_proto_rawDescGZIP(), []int{21, 0, 0}
}

func (x *PbEolianAvatar_HandsData_HandData) GetShow() bool {
	if x != nil {
		return x.Show
	}
	return false
}

func (x *PbEolianAvatar_HandsData_HandData) GetJoints() map[uint32]*PbEolianAvatar_HandsData_HandData_JointData {
	if x != nil {
		return x.Joints
	}
	return nil
}

type PbEolianAvatar_HandsData_HandData_JointData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Position *PbVect3 `protobuf:"bytes,1,opt,name=position,proto3,oneof" json:"position,omitempty"`
	Active   bool     `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
}

func (x *PbEolianAvatar_HandsData_HandData_JointData) Reset() {
	*x = PbEolianAvatar_HandsData_HandData_JointData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MuncRoom_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PbEolianAvatar_HandsData_HandData_JointData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbEolianAvatar_HandsData_HandData_JointData) ProtoMessage() {}

func (x *PbEolianAvatar_HandsData_HandData_JointData) ProtoReflect() protoreflect.Message {
	mi := &file_MuncRoom_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbEolianAvatar_HandsData_HandData_JointData.ProtoReflect.Descriptor instead.
func (*PbEolianAvatar_HandsData_HandData_JointData) Descriptor() ([]byte, []int) {
	return file_MuncRoom_proto_rawDescGZIP(), []int{21, 0, 0, 0}
}

func (x *PbEolianAvatar_HandsData_HandData_JointData) GetPosition() *PbVect3 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *PbEolianAvatar_HandsData_HandData_JointData) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

var File_MuncRoom_proto protoreflect.FileDescriptor

var file_MuncRoom_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x4d, 0x75, 0x6e, 0x63, 0x52, 0x6f, 0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4f, 0x0a, 0x11, 0x43,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x71,
	0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x2c, 0x0a, 0x12,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x2c, 0x0a, 0x10, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x35, 0x0a, 0x17, 0x52, 0x65, 0x6c, 0x65,
	0x61, 0x73, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x73,
	0x68, 0x69, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x22,
	0x86, 0x01, 0x0a, 0x0f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x6f, 0x6f, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x37, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x6f,
	0x6f, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x1a, 0x3a, 0x0a, 0x0c,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x64, 0x0a, 0x0e, 0x52, 0x6f, 0x6f, 0x6d,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69,
	0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69,
	0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x5f,
	0x0a, 0x0f, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x30, 0x0a,
	0x0c, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x50, 0x62, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x52, 0x0c, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22,
	0x74, 0x0a, 0x0b, 0x52, 0x6f, 0x6f, 0x6d, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x22,
	0x0a, 0x0c, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x6f,
	0x72, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x6f, 0x69, 0x70, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x76, 0x6f, 0x69, 0x70, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x25,
	0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x09, 0x2e, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x52, 0x08, 0x70, 0x6c, 0x61,
	0x74, 0x66, 0x6f, 0x72, 0x6d, 0x22, 0x66, 0x0a, 0x0c, 0x52, 0x6f, 0x6f, 0x6d, 0x4a, 0x6f, 0x69,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2e, 0x0a, 0x12, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x12, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x76, 0x6f, 0x69, 0x70, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x76,
	0x6f, 0x69, 0x70, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x22, 0x3c, 0x0a,
	0x0b, 0x50, 0x62, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x2d, 0x0a, 0x0a,
	0x61, 0x6c, 0x6c, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x45, 0x76, 0x74, 0x52,
	0x0a, 0x61, 0x6c, 0x6c, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x22, 0x69, 0x0a, 0x0c, 0x52,
	0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x45, 0x76, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x23, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x09, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4f, 0x62, 0x6a, 0x52, 0x07, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x3a, 0x0a, 0x08, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4f,
	0x62, 0x6a, 0x12, 0x2e, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x22, 0xbc, 0x01, 0x0a, 0x0a, 0x50, 0x62, 0x4d, 0x75, 0x6e, 0x63, 0x55, 0x73, 0x65,
	0x72, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a,
	0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x09, 0x2e, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x48, 0x00, 0x52, 0x08, 0x70, 0x6c,
	0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x88, 0x01, 0x01, 0x12, 0x37, 0x0a, 0x0d, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x50, 0x62, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x48, 0x01,
	0x52, 0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x88,
	0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x42,
	0x10, 0x0a, 0x0e, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x44, 0x61, 0x74,
	0x61, 0x22, 0xcc, 0x01, 0x0a, 0x0c, 0x50, 0x62, 0x4d, 0x75, 0x6e, 0x63, 0x41, 0x76, 0x61, 0x74,
	0x61, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x88, 0x01, 0x01, 0x12, 0x2a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x48, 0x01, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x88, 0x01, 0x01, 0x12,
	0x37, 0x0a, 0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x44, 0x61, 0x74, 0x61,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x50, 0x62, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x66, 0x6f, 0x72, 0x6d, 0x48, 0x02, 0x52, 0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72,
	0x6d, 0x44, 0x61, 0x74, 0x61, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x42, 0x10,
	0x0a, 0x0e, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x44, 0x61, 0x74, 0x61,
	0x22, 0xac, 0x01, 0x0a, 0x0b, 0x50, 0x62, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d,
	0x12, 0x29, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x08, 0x2e, 0x50, 0x62, 0x56, 0x65, 0x63, 0x74, 0x33, 0x48, 0x00, 0x52, 0x08,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x29, 0x0a, 0x08, 0x72,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e,
	0x50, 0x62, 0x56, 0x65, 0x63, 0x74, 0x33, 0x48, 0x01, 0x52, 0x08, 0x72, 0x6f, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x23, 0x0a, 0x05, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x50, 0x62, 0x56, 0x65, 0x63, 0x74, 0x33, 0x48,
	0x02, 0x52, 0x05, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x72, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x22,
	0x33, 0x0a, 0x07, 0x50, 0x62, 0x56, 0x65, 0x63, 0x74, 0x33, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x01, 0x7a, 0x22, 0x85, 0x01, 0x0a, 0x11, 0x55, 0x73, 0x65, 0x72, 0x4a, 0x6f, 0x69,
	0x6e, 0x65, 0x64, 0x52, 0x6f, 0x6f, 0x6d, 0x45, 0x76, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65,
	0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0b, 0x72, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x22, 0x85, 0x01, 0x0a,
	0x0f, 0x55, 0x73, 0x65, 0x72, 0x45, 0x78, 0x69, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x45, 0x76, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x6f, 0x6d,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6f, 0x6d,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x22, 0x0a, 0x0c, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x65, 0x64, 0x22, 0x45, 0x0a, 0x0b, 0x45, 0x78, 0x69, 0x74, 0x52, 0x6f, 0x6f, 0x6d,
	0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2a, 0x0a, 0x0c, 0x52,
	0x6f, 0x6f, 0x6d, 0x45, 0x78, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x72,
	0x6f, 0x6f, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72,
	0x6f, 0x6f, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x2d, 0x0a, 0x0f, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x22, 0xbf, 0x07, 0x0a, 0x0e, 0x50, 0x62, 0x45, 0x6f, 0x6c,
	0x69, 0x61, 0x6e, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72,
	0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f,
	0x72, 0x6d, 0x48, 0x00, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x88, 0x01,
	0x01, 0x12, 0x37, 0x0a, 0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x44, 0x61,
	0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x50, 0x62, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x48, 0x01, 0x52, 0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66,
	0x6f, 0x72, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x88, 0x01, 0x01, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x3f, 0x0a, 0x08, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x50, 0x62, 0x45, 0x6f, 0x6c, 0x69, 0x61,
	0x6e, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x2e, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x53, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x48, 0x02, 0x52, 0x08, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x73, 0x88, 0x01, 0x01, 0x12, 0x34, 0x0a, 0x05, 0x68, 0x61, 0x6e, 0x64, 0x73, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x50, 0x62, 0x45, 0x6f, 0x6c, 0x69, 0x61, 0x6e, 0x41,
	0x76, 0x61, 0x74, 0x61, 0x72, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x44, 0x61, 0x74, 0x61, 0x48,
	0x03, 0x52, 0x05, 0x68, 0x61, 0x6e, 0x64, 0x73, 0x88, 0x01, 0x01, 0x1a, 0xc9, 0x03, 0x0a, 0x09,
	0x48, 0x61, 0x6e, 0x64, 0x73, 0x44, 0x61, 0x74, 0x61, 0x12, 0x3b, 0x0a, 0x04, 0x6c, 0x65, 0x66,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x50, 0x62, 0x45, 0x6f, 0x6c, 0x69,
	0x61, 0x6e, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x44, 0x61,
	0x74, 0x61, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x04, 0x6c,
	0x65, 0x66, 0x74, 0x88, 0x01, 0x01, 0x12, 0x3d, 0x0a, 0x05, 0x72, 0x69, 0x67, 0x68, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x50, 0x62, 0x45, 0x6f, 0x6c, 0x69, 0x61, 0x6e,
	0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x44, 0x61, 0x74, 0x61,
	0x2e, 0x48, 0x61, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x61, 0x48, 0x01, 0x52, 0x05, 0x72, 0x69, 0x67,
	0x68, 0x74, 0x88, 0x01, 0x01, 0x1a, 0xac, 0x02, 0x0a, 0x08, 0x48, 0x61, 0x6e, 0x64, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x68, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x04, 0x73, 0x68, 0x6f, 0x77, 0x12, 0x46, 0x0a, 0x06, 0x6a, 0x6f, 0x69, 0x6e, 0x74, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x50, 0x62, 0x45, 0x6f, 0x6c, 0x69, 0x61,
	0x6e, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x44, 0x61, 0x74,
	0x61, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x74,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x6a, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x1a, 0x5b,
	0x0a, 0x09, 0x4a, 0x6f, 0x69, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x29, 0x0a, 0x08, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e,
	0x50, 0x62, 0x56, 0x65, 0x63, 0x74, 0x33, 0x48, 0x00, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x42, 0x0b,
	0x0a, 0x09, 0x5f, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x67, 0x0a, 0x0b, 0x4a,
	0x6f, 0x69, 0x6e, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x42, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x50, 0x62,
	0x45, 0x6f, 0x6c, 0x69, 0x61, 0x6e, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x2e, 0x48, 0x61, 0x6e,
	0x64, 0x73, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x61, 0x2e,
	0x4a, 0x6f, 0x69, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6c, 0x65, 0x66, 0x74, 0x42, 0x08, 0x0a,
	0x06, 0x5f, 0x72, 0x69, 0x67, 0x68, 0x74, 0x1a, 0x88, 0x01, 0x0a, 0x0e, 0x41, 0x76, 0x61, 0x74,
	0x61, 0x72, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x68,
	0x6f, 0x77, 0x42, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x73, 0x68,
	0x6f, 0x77, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x75, 0x74, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x6d, 0x75, 0x74, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x68, 0x61,
	0x73, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a,
	0x68, 0x61, 0x73, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x12, 0x26, 0x0a, 0x0e, 0x68, 0x61,
	0x73, 0x4d, 0x65, 0x6e, 0x75, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0e, 0x68, 0x61, 0x73, 0x4d, 0x65, 0x6e, 0x75, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x42,
	0x10, 0x0a, 0x0e, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x44, 0x61, 0x74,
	0x61, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x42, 0x08,
	0x0a, 0x06, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x73, 0x2a, 0x4c, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x45, 0x53, 0x4b, 0x54, 0x4f, 0x50, 0x10,
	0x00, 0x12, 0x0c, 0x0a, 0x08, 0x48, 0x4f, 0x4c, 0x4f, 0x4c, 0x45, 0x4e, 0x53, 0x10, 0x01, 0x12,
	0x0a, 0x0a, 0x06, 0x54, 0x41, 0x42, 0x4c, 0x45, 0x54, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x4d,
	0x41, 0x47, 0x49, 0x43, 0x5f, 0x4c, 0x45, 0x41, 0x50, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x51,
	0x55, 0x45, 0x53, 0x54, 0x10, 0x04, 0x42, 0x0f, 0x5a, 0x0d, 0x6d, 0x75, 0x6e, 0x63, 0x2f, 0x72,
	0x6f, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_MuncRoom_proto_rawDescOnce sync.Once
	file_MuncRoom_proto_rawDescData = file_MuncRoom_proto_rawDesc
)

func file_MuncRoom_proto_rawDescGZIP() []byte {
	file_MuncRoom_proto_rawDescOnce.Do(func() {
		file_MuncRoom_proto_rawDescData = protoimpl.X.CompressGZIP(file_MuncRoom_proto_rawDescData)
	})
	return file_MuncRoom_proto_rawDescData
}

var file_MuncRoom_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_MuncRoom_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_MuncRoom_proto_goTypes = []interface{}{
	(Platform)(0),                                       // 0: Platform
	(*ConnectionInitReq)(nil),                           // 1: ConnectionInitReq
	(*ConnectionInitResp)(nil),                          // 2: ConnectionInitResp
	(*ObjectUpdateResp)(nil),                            // 3: ObjectUpdateResp
	(*ReleaseObjectsOwnership)(nil),                     // 4: ReleaseObjectsOwnership
	(*RequestBoolResp)(nil),                             // 5: RequestBoolResp
	(*RoomConnectReq)(nil),                              // 6: RoomConnectReq
	(*RoomConnectResp)(nil),                             // 7: RoomConnectResp
	(*RoomJoinReq)(nil),                                 // 8: RoomJoinReq
	(*RoomJoinResp)(nil),                                // 9: RoomJoinResp
	(*PbRoomState)(nil),                                 // 10: PbRoomState
	(*RoomStateEvt)(nil),                                // 11: RoomStateEvt
	(*StateObj)(nil),                                    // 12: StateObj
	(*PbMuncUser)(nil),                                  // 13: PbMuncUser
	(*PbMuncAvatar)(nil),                                // 14: PbMuncAvatar
	(*PbTransform)(nil),                                 // 15: PbTransform
	(*PbVect3)(nil),                                     // 16: PbVect3
	(*UserJoinedRoomEvt)(nil),                           // 17: UserJoinedRoomEvt
	(*UserExitRoomEvt)(nil),                             // 18: UserExitRoomEvt
	(*ExitRoomReq)(nil),                                 // 19: ExitRoomReq
	(*RoomExitResp)(nil),                                // 20: RoomExitResp
	(*ObjectDeleteReq)(nil),                             // 21: ObjectDeleteReq
	(*PbEolianAvatar)(nil),                              // 22: PbEolianAvatar
	nil,                                                 // 23: RequestBoolResp.ResultsEntry
	(*PbEolianAvatar_HandsData)(nil),                    // 24: PbEolianAvatar.HandsData
	(*PbEolianAvatar_AvatarSettings)(nil),               // 25: PbEolianAvatar.AvatarSettings
	(*PbEolianAvatar_HandsData_HandData)(nil),           // 26: PbEolianAvatar.HandsData.HandData
	(*PbEolianAvatar_HandsData_HandData_JointData)(nil), // 27: PbEolianAvatar.HandsData.HandData.JointData
	nil,               // 28: PbEolianAvatar.HandsData.HandData.JointsEntry
	(*anypb.Any)(nil), // 29: google.protobuf.Any
}
var file_MuncRoom_proto_depIdxs = []int32{
	23, // 0: RequestBoolResp.results:type_name -> RequestBoolResp.ResultsEntry
	10, // 1: RoomConnectResp.currentState:type_name -> PbRoomState
	0,  // 2: RoomJoinReq.platform:type_name -> Platform
	11, // 3: PbRoomState.allObjects:type_name -> RoomStateEvt
	12, // 4: RoomStateEvt.payload:type_name -> StateObj
	29, // 5: StateObj.payload:type_name -> google.protobuf.Any
	0,  // 6: PbMuncUser.platform:type_name -> Platform
	15, // 7: PbMuncUser.transformData:type_name -> PbTransform
	0,  // 8: PbMuncAvatar.platform:type_name -> Platform
	15, // 9: PbMuncAvatar.transformData:type_name -> PbTransform
	16, // 10: PbTransform.position:type_name -> PbVect3
	16, // 11: PbTransform.rotation:type_name -> PbVect3
	16, // 12: PbTransform.scale:type_name -> PbVect3
	0,  // 13: PbEolianAvatar.platform:type_name -> Platform
	15, // 14: PbEolianAvatar.transformData:type_name -> PbTransform
	25, // 15: PbEolianAvatar.settings:type_name -> PbEolianAvatar.AvatarSettings
	24, // 16: PbEolianAvatar.hands:type_name -> PbEolianAvatar.HandsData
	26, // 17: PbEolianAvatar.HandsData.left:type_name -> PbEolianAvatar.HandsData.HandData
	26, // 18: PbEolianAvatar.HandsData.right:type_name -> PbEolianAvatar.HandsData.HandData
	28, // 19: PbEolianAvatar.HandsData.HandData.joints:type_name -> PbEolianAvatar.HandsData.HandData.JointsEntry
	16, // 20: PbEolianAvatar.HandsData.HandData.JointData.position:type_name -> PbVect3
	27, // 21: PbEolianAvatar.HandsData.HandData.JointsEntry.value:type_name -> PbEolianAvatar.HandsData.HandData.JointData
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_MuncRoom_proto_init() }
func file_MuncRoom_proto_init() {
	if File_MuncRoom_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_MuncRoom_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectionInitReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MuncRoom_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectionInitResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MuncRoom_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectUpdateResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MuncRoom_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReleaseObjectsOwnership); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MuncRoom_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestBoolResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MuncRoom_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomConnectReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MuncRoom_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomConnectResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MuncRoom_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomJoinReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MuncRoom_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomJoinResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MuncRoom_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PbRoomState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MuncRoom_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomStateEvt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MuncRoom_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StateObj); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MuncRoom_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PbMuncUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MuncRoom_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PbMuncAvatar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MuncRoom_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PbTransform); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MuncRoom_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PbVect3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MuncRoom_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserJoinedRoomEvt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MuncRoom_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserExitRoomEvt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MuncRoom_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExitRoomReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MuncRoom_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomExitResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MuncRoom_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectDeleteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MuncRoom_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PbEolianAvatar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MuncRoom_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PbEolianAvatar_HandsData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MuncRoom_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PbEolianAvatar_AvatarSettings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MuncRoom_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PbEolianAvatar_HandsData_HandData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MuncRoom_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PbEolianAvatar_HandsData_HandData_JointData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_MuncRoom_proto_msgTypes[12].OneofWrappers = []interface{}{}
	file_MuncRoom_proto_msgTypes[13].OneofWrappers = []interface{}{}
	file_MuncRoom_proto_msgTypes[14].OneofWrappers = []interface{}{}
	file_MuncRoom_proto_msgTypes[21].OneofWrappers = []interface{}{}
	file_MuncRoom_proto_msgTypes[23].OneofWrappers = []interface{}{}
	file_MuncRoom_proto_msgTypes[26].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_MuncRoom_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_MuncRoom_proto_goTypes,
		DependencyIndexes: file_MuncRoom_proto_depIdxs,
		EnumInfos:         file_MuncRoom_proto_enumTypes,
		MessageInfos:      file_MuncRoom_proto_msgTypes,
	}.Build()
	File_MuncRoom_proto = out.File
	file_MuncRoom_proto_rawDesc = nil
	file_MuncRoom_proto_goTypes = nil
	file_MuncRoom_proto_depIdxs = nil
}
